### ISSUE TITLE
Cloudformation cannot create.

### ISSUE THREAD

**Issue by jinleileiking** [aws-samples/amazon-ivs-auto-captions-web-demo#11]
run `bash deploy.sh` error:

console:

<img width="1855" alt="image" src="https://user-images.githubusercontent.com/93968/197499030-d660ca3b-4b5b-4540-9fd8-099b6cc0972e.png">

aws console:
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/93968/197498921-8bfdae6d-8e27-458c-9e42-bb4f25b65669.png">

**Comment by jinleileiking** [comment]
I change from us-east-2 to us-east-1 , problem sovled....

**Comment by mboulin** [comment]
Glad you were able to deploy the solution successfully. Closing the issue.
