### ISSUE TITLE
Is there a discussion group for these examples?

### ISSUE THREAD

**Issue by jkbredsquiggles** [aws-samples/amazon-ivs-auto-captions-web-demo#12]
I apologize if this is not the correct place to ask - I glanced at repost and tried googling and nothing obvious appeared.

I'm playing with the code in this example and have some questions about design choices, e.g. using web sockets for the communications between the translate and transcribe servers and the send transcription lambda, instead of say SNS.

I don't want to bother the developers (beyond asking this question) as:

- This project an illustrative example and, as pointed out, not a production ready service, 
- So  I don't expect each design choice to have been fully examined, 
- And I'd rather they create more of these types of things than waste their time defending design choices 

 But, I also wouldn't mind discussing, why certain things were done certain ways as a way to figure out best practices.

So, can you point me to a discussion group? 

Thanks.

**Comment by mboulin** [comment]
Thank you for your question. Our code samples typically only highlight one possible way – out of many – to implement a given solution. While we cannot offer judgement or compare services used for a given solution, I would encourage you to join a [AWS user group](https://aws.amazon.com/developer/community/) in your region and/or look into the [AWS Community Builders program](https://aws.amazon.com/developer/community/community-builders/community-builders-directory/) as well as [AWS Heroes](https://aws.amazon.com/developer/community/heroes/), which may offer you venues to dig into the specifics of reference implementations and discuss overall best practices.
