### ISSUE TITLE
js v3? can i still use v2?

### ISSUE THREAD

**Issue by turi4200** [aws-samples/amazon-ivs-auto-captions-web-demo#13]
NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).

**Comment by mboulin** [comment]
Thanks for opening this issue. We'll take this request into consideration and may update this demo to use the SDK v3 in the future.
