### ISSUE TITLE
Failed to build images

### ISSUE THREAD

**Issue by cneira84** [aws-samples/amazon-ivs-auto-captions-web-demo#14]
Hi team. Please add this line to the docker file for Stream Server

`RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list`

Or change the base image please.

Regards!

**Comment by andreido** [comment]
Hello @cneira84,

The latest merge (https://github.com/aws-samples/amazon-ivs-auto-captions-web-demo/pull/18) addresses this issue.

Thank you!
