### ISSUE TITLE
Any plans for AWS IVS to support this feature natively?

### ISSUE THREAD

**Issue by abhijeet-toptal** [aws-samples/amazon-ivs-auto-captions-web-demo#17]
All other providers offer this out of the box like Azure, Zoom, 100ms, Agora etc. Will AWS IVS support this out of the box?

**Comment by mboulin** [comment]
Thank you for your suggestion and feedback! We appreciate your interest in Amazon IVS and the features it provides. We will take your suggestion into consideration as we continue to improve our services. However, we cannot make any promises or comment on future plans or features.

Note that feature requests are outside the scope of demos and code samples we provide on GitHub. If you have further suggestions or need more detailed assistance, we recommend engaging with your AWS Account team or Associate AM if you have one.

Thank you for your understanding.
