### ISSUE TITLE
Can't change transcribe to another language

### ISSUE THREAD

**Issue by TimLuminesence** [aws-samples/amazon-ivs-auto-captions-web-demo#3]
We want to use Chinese transcribe. Basically, people speak Chinese and get transcribe. 
Tried to following suggestion to change 
"This demo was built with English (en-US) as the language used for auto-captions.
You can change the default language/locale by editing LANGUAGE_CODE, DEFAULT_LANGUAGE_CODE and
MEDIA_SAMPLE_RATE_HERTZ in the constant.js file.

You can see a list of supported languages by Amazon Transcribe here: https://docs.aws.amazon.com/transcribe/latest/dg/supported-languages.html"

Diff is like following.
1. in ./serverless/transcribe-server/src/constants.js
change 
  LANGUAGE_CODE: process.env.LANGUAGE_CODE ?? "en-US",
to
  LANGUAGE_CODE: process.env.LANGUAGE_CODE ?? "zh-CN",

change
    MEDIA_SAMPLE_RATE_HERTZ:
    process.env.LANGUAGE_CODE == "en-US" || process.env.LANGUAGE_CODE == "es-US"
to
    MEDIA_SAMPLE_RATE_HERTZ:
    process.env.LANGUAGE_CODE == "zh-CN" || process.env.LANGUAGE_CODE == "zh-CN"

change 
    DEFAULT_LANGUAGE_CODE: "en",
to
    DEFAULT_LANGUAGE_CODE: "zh",

2. in ./serverless/translate-server/src/constants.js
change
     DEFAULT_SOURCE_LANGUAGE_CODE: "en",
to
     DEFAULT_SOURCE_LANGUAGE_CODE: "zh",

3. in ./deployment/translate-languages.json
add
     "English [en]": true,

4. in ./serverless/transcribe-server/build/task-definition-dev.json
change 
    "value": "en-US"
to
    "value": "zh-CN"

5. in ./serverless/transcribe-server/build/task-definition-prod.json
change
     "value": "en-US"
to
      "value": "zh-CN"

But didn't seem to work. 
Do I miss any file that need to change but I didn't?
Also tired to just change 1 ./serverless/transcribe-server/src/constants.js, and doesn't work neither. 
Do you have any idea how can I make it work with another language? 
Thanks a lot!

**Comment by mboulin** [comment]
@TimLuminesence Unfortunately, the demo as-built doesn't reliably support changing the default language at this time, as the focus was to provide a sample solution for en-US. We recently uncovered that changing the settings in the files mentioned isn't enough to support that use case. Supporting a different language (especially non-latin languages) reliably would require additional work that is outside of scope for this demo. 
We might revisit this in the future and provide an update to the demo to support different default languages.

**Comment by TimLuminesence** [comment]
Thanks @mboulin for the update.

**Comment by TimLuminesence** [comment]
@mboulin Do you have any idea why the demo can't easily change to support speak Chinese and get transcript? The AWS transcript should support Chinese audio to text, right? Do you have any idea how can I modify the demo to support speak Chinese and get transcript? Thanks a lot!
